include themes/mocha.conf

# Tab bar styling (from catppuccin/kitty README)
tab_bar_min_tabs            1
tab_bar_edge                bottom
tab_bar_style               powerline
tab_powerline_style         slanted
tab_title_template          {title}{' :{}:'.format(num_windows) if num_windows > 1 else ''}

window_padding_width 5
hide_window_decorations yes
background_opacity 0.8
font_family MesloLGL Nerd Font Mono
font_size 13.5
remember_window_size no
confirm_os_window_close 0
shell fish
cursor_trail 1
cursor_shape block
shell_integration no-cursor